# Generated by Django 4.2.2 on 2024-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=300)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('escore', models.TextField(default='')),
                ('ecoobj', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300)),
                ('username', models.TextField(max_length=255)),
                ('email', models.TextField(default=0.0)),
                ('phone', models.TextField(default=0.0)),
                ('preferencelist', models.TextField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
